# a github action to run main.py every day and push the results to main branch
name: Run daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        env:
          KEY: ${{ secrets.KEY }}
          SECRET: ${{ secrets.SECRET }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
        env:
          KEY: ${{ secrets.KEY }}
          SECRET: ${{ secrets.SECRET }}
          USE_PROXY: ${{ secrets.USE_PROXY }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "upd: $(date '+%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main